version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - yidongnan
  ignore:
  - dependency-name: com.google.protobuf:protoc
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: io.grpc:protoc-gen-grpc-java
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: io.grpc:grpc-stub
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: io.grpc:grpc-protobuf
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: io.grpc:grpc-netty
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR10
    - Hoxton.SR9
  - dependency-name: com.google.protobuf:protobuf-gradle-plugin
    versions:
    - 0.8.14
    - 0.8.15
  - dependency-name: net.devh:grpc-server-spring-boot-starter
    versions:
    - 2.10.1.RELEASE
  - dependency-name: net.devh:grpc-client-spring-boot-starter
    versions:
    - 2.10.1.RELEASE
